create table iso3166 (
	code varchar(10) CONSTRAINT firstkey PRIMARY KEY
	,country varchar(100)
	,continent varchar(100)
	,region varchar(100)
	,capital varchar(100)
);
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','Afghanistan','Kabul','AF');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Albania','Tirana','AL');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Northern Africa','Algeria','Algiers','DZ');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','American Samoa','Pago Pago','AS');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South West Europe','Andorra','Andorra la Vella','AD');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Angola','Luanda','AO');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Anguilla','The Valley','AI');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Antigua and Barbuda','Saint John''s','AG');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Argentina','Buenos Aires','AR');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Armenia','Yerevan','AM');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Aruba','Oranjestad','AW');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Australia','Canberra','AU');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Central Europe','Austria','Vienna','AT');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Azerbaijan','Baku (Baki)','AZ');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Bahamas, The','Nassau','BS');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Bahrain','Manama','BH');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','Bangladesh','Dhaka','BD');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Barbados','Bridgetown','BB');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Eastern Europe','Belarus','Minsk','BY');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Belgium','Brussels','BE');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','Central America','Belize','Belmopan','BZ');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Benin','Porto-Novo ³','BJ');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Bermuda','Hamilton','BM');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','Bhutan','Thimphu','BT');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Bolivia','La Paz / Sucre','BO');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Bosnia and Herzegovina','Sarajevo','BA');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Botswana','Gaborone','BW');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Brazil','Brasilia','BR');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','British Virgin Islands','Road Town','VG');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Brunei','Bandar Seri Begawan','BN');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Bulgaria','Sofia','BG');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Burkina Faso','Ouagadougou','BF');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Central Africa','Burundi','Bujumbura','BI');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Cambodia','Phnom Penh','KH');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Cameroon','Yaounde','CM');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','North America','Canada','Ottawa','CA');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Cape Verde','Praia','CV');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Cayman Islands','George Town','KY');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Central Africa','Central African Republic','Bangui','CF');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Central Africa','Chad','N''Djamena','TD');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Chile','Santiago','CL');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','East Asia','China','Beijing','CN');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Christmas Island','The Settlement','CX');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Cocos (Keeling) Islands','West Island','CC');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Colombia','Bogota','CO');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Indian Ocean','Comoros','Moroni','KM');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Central Africa','Congo, Republic of the','Brazzaville','CD');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Cook Islands','Avarua','CK');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','Central America','Costa Rica','San Jose','CR');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Cote d''Ivoire','Yamoussoukro','CI');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Croatia','Zagreb','HR');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Cuba','Havana','CU');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Cyprus','Nicosia','CY');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Central Europe','Czech Republic','Prague','CZ');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Northern Europe','Denmark','Copenhagen','DK');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Eastern Africa','Djibouti','Djibouti','DJ');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Dominica','Roseau','DM');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Dominican Republic','Santo Domingo','DO');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Ecuador','Quito','EC');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Northern Africa','Egypt','Cairo','EG');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','Central America','El Salvador','San Salvador','SV');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Equatorial Guinea','Malabo','GQ');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Eastern Africa','Eritrea','Asmara','ER');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Eastern Europe','Estonia','Tallinn','EE');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Eastern Africa','Ethiopia','Addis Ababa','ET');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Falkland Islands (Islas Malvinas)','Stanley','FK');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Northern Europe','Faroe Islands','Torshavn','FO');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Fiji','Suva','FJ');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Northern Europe','Finland','Helsinki','FI');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','France','Paris','FR');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','French Guiana','Cayenne','GF');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','French Polynesia','Papeete','PF');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Gabon','Libreville','GA');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Gambia, The','Banjul','GM');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Georgia','T''bilisi','GE');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Germany','Berlin','DE');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Ghana','Accra','GH');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South West Europe','Gibraltar','Gibraltar','GI');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Greece','Athens','GR');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','North America','Greenland','Nuuk (Godthab)','GL');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Grenada','Saint George''s','GD');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Guadeloupe','Basse-Terre','GP');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Guam','Hagatna (Agana)','GU');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','Central America','Guatemala','Guatemala','GT');
--insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Guernsey','Saint Peter Port','--');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Guinea','Conakry','GN');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Guinea-Bissau','Bissau','GW');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Guyana','Georgetown','GY');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Haiti','Port-au-Prince','HT');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Southern Europe','Holy See (Vatican City)','Vatican City','VA');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','Central America','Honduras','Tegucigalpa','HN');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Central Europe','Hungary','Budapest','HU');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Northern Europe','Iceland','Reykjavik','IS');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','India','New Delhi','IN');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Indonesia','Jakarta','ID');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Iran','Tehran','IR');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Iraq','Baghdad','IQ');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Ireland','Dublin','IE');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Israel','Jerusalem','IL');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Southern Europe','Italy','Rome','IT');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Jamaica','Kingston','JM');
--insert into iso3166 (continent,region,country,capital,code) values ('Europe','Northern Europe','Jan Mayen','-','--');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','East Asia','Japan','Tokyo','JP');
--insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Jersey','Saint Helier','--');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Jordan','Amman','JO');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','Central Asia','Kazakhstan','Astana (Akmola)','KZ');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Eastern Africa','Kenya','Nairobi','KE');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Kiribati','Tarawa','KI');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','East Asia','Korea, North','P''yongyang','KP');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','East Asia','Korea, South','Seoul','KR');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Kuwait','Kuwait','KW');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','Central Asia','Kyrgyzstan','Bishkek','KG');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Laos','Vientiane','LA');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Eastern Europe','Latvia','Riga','LV');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Lebanon','Beirut','LB');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Lesotho','Maseru','LS');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Liberia','Monrovia','LR');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Northern Africa','Libya','Tripoli','LY');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Central Europe','Liechtenstein','Vaduz','LI');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Eastern Europe','Lithuania','Vilnius','LT');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Luxembourg','Luxembourg','LU');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Macedonia','Skopje','MK');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Indian Ocean','Madagascar','Antananarivo','MG');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Malawi','Lilongwe','MW');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Malaysia','Kuala Lumpur','MY');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','Maldives','Male (Maale)','MV');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Mali','Bamako','ML');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Southern Europe','Malta','Valletta','MT');
--insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Man, Isle of','Douglas','--');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Marshall Islands','Majuro','MH');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Martinique','Fort-de-France','MQ');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Mauritania','Nouakchott','MR');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Indian Ocean','Mauritius','Port Louis','MU');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Indian Ocean','Mayotte','Mamoutzou','YT');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','Central America','Mexico','Mexico','MX');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Micronesia, Federated States of','Palikir','FM');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Eastern Europe','Moldova','Chisinau','MD');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Monaco','Monaco','MC');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','Northern Asia','Mongolia','Ulaanbaatar','MN');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Montserrat','Plymouth','MS');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Northern Africa','Morocco','Rabat','MA');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Mozambique','Maputo','MZ');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Myanmar (Burma)','Rangoon (Yangon)','MM');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Namibia','Windhoek','NA');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Nauru','no official capital','NR');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','Nepal','Kathmandu','NP');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Netherlands','Amsterdam','NL');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Netherlands Antilles','Willemstad','AN');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','New Caledonia','Noumea','NC');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','New Zealand','Wellington','NZ');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','Central America','Nicaragua','Managua','NI');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Niger','Niamey','NE');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Nigeria','Abuja','NG');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Niue','Alofi','NU');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Norfolk Island','Kingston','NF');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Northern Mariana Islands','Saipan','MP');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Northern Europe','Norway','Oslo','NO');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Oman','Muscat','OM');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','Pakistan','Islamabad','PK');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Palau','Koror','PW');
--insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Palestine','','--');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','Central America','Panama','Panama','PA');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Papua New Guinea','Port Moresby','PG');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Paraguay','Asuncion','PY');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Peru','Lima','PE');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Philippines','Manila','PH');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Pitcairn Islands','Adamstown','PN');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Eastern Europe','Poland','Warsaw','PL');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South West Europe','Portugal','Lisbon','PT');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Puerto Rico','San Juan','PR');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Qatar','Doha','QA');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Indian Ocean','Reunion','Saint-Denis','RE');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Romania','Bucharest','RO');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','Northern Asia','Russia','Moscow','RU');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Central Africa','Rwanda','Kigali','RW');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Saint Kitts and Nevis','Basseterre','KN');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Saint Lucia','Castries','LC');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','North America','Saint Pierre and Miquelon','Saint-Pierre','PM');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Saint Vincent and the Grenadines','Kingstown','VC');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Southern Europe','San Marino','San Marino','SM');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Sao Tome and Principe','Sao Tome','ST');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Saudi Arabia','Riyadh','SA');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Senegal','Dakar','SN');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Serbia and Montenegro','Belgrade / Podgorica','RS');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Indian Ocean','Seychelles','Victoria','SC');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Sierra Leone','Freetown','SL');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Singapore','Singapore','SG');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Central Europe','Slovakia','Bratislava','SK');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Slovenia','Ljubljana','SI');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Solomon Islands','Honiara','SB');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Eastern Africa','Somalia','Mogadishu','SO');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','South Africa','Pretoria ¹','ZA');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South West Europe','Spain','Madrid','ES');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','Sri Lanka','Colombo','LK');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Northern Africa','Sudan','Khartoum','SD');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Suriname','Paramaribo','SR');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Northern Europe','Svalbard','Longyearbyen','SJ');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Swaziland','Mbabane ²','SZ');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Northern Europe','Sweden','Stockholm','SE');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Central Europe','Switzerland','Bern','CH');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Syria','Damascus','SY');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','East Asia','Taiwan','Taipei','TW');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','Central Asia','Tajikistan','Dushanbe','TJ');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Eastern Africa','Tanzania','Dar es Salaam','TZ');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Thailand','Bangkok','TH');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Western Africa','Togo','Lome','TG');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Tokelau','none','TK');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Tonga','Nuku''alofa','TO');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Trinidad and Tobago','Port-of-Spain','TT');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Northern Africa','Tunisia','Tunis','TN');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Turkey','Ankara','TR');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','Central Asia','Turkmenistan','Ashgabat','TM');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Turks and Caicos Islands','Grand Turk','TC');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Tuvalu','Funafuti','TV');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Eastern Africa','Uganda','Kampala','UG');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Eastern Europe','Ukraine','Kiev','UA');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','United Arab Emirates','Abu Dhabi','AE');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','United Kingdom','London','GB');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','North America','United States','Washington, DC','US');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Uruguay','Montevideo','UY');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','Central Asia','Uzbekistan','Tashkent (Toshkent)','UZ');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Vanuatu','Port-Vila','VU');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','South America','Venezuela','Caracas','VE');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','Vietnam','Hanoi','VN');
insert into iso3166 (continent,region,country,capital,code) values ('Americas','West Indies','Virgin Islands','Charlotte Amalie','VI');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Wallis and Futuna','Mata-Utu (on Ile Uvea)','WF');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Northern Africa','Western Sahara','none','EH');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','Pacific','Western Samoa','Apia','WS');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South West Asia','Yemen','Sanaa','YE');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Central Africa','Zaire (Dem Rep of Congo)','Kinshasa','ZR');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Zambia','Lusaka','ZM');
insert into iso3166 (continent,region,country,capital,code) values ('Africa','Southern Africa','Zimbabwe','Harare','ZW');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','East Asia','Hong Kong (China)','Victoria','HK');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','East Asia','Macau (China)','Macau','MO');
insert into iso3166 (continent,region,country,capital,code) values ('Antarctica','Antarctica','Antarctica','','AQ');
insert into iso3166 (continent,region,country,capital,code) values ('Atlantic Ocean','South Atlantic Ocean','Bouvet Island','','BV');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South Asia','British Indian Ocean Territory','','IO');
insert into iso3166 (continent,region,country,capital,code) values ('Asia','South East Asia','East Timor','','TP');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','France, Metropolitan','','FX');
insert into iso3166 (continent,region,country,capital,code) values ('Indian Ocean','Southern Indian Ocean','French Southern and Antarctic Lands','','TF');
insert into iso3166 (continent,region,country,capital,code) values ('Indian Ocean','Southern Indian Ocean','Heard Island and McDonald Islands','','HM');
--insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Montenegro','','--');
insert into iso3166 (continent,region,country,capital,code) values ('Atlantic Ocean','South Atlantic Ocean','Saint Helena','','SH');
insert into iso3166 (continent,region,country,capital,code) values ('Atlantic Ocean','South Atlantic Ocean','South Georgia and the South Sandwich Islands','','GS');
insert into iso3166 (continent,region,country,capital,code) values ('Oceania','North Pacific Ocean','United States Minor Outlying Islands','','UM');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','South East Europe','Yugoslavia*','','YU');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','England','London','GB-ENG');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Northern Ireland','Belfast','GB-NIR');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Scotland','Edinburgh','GB-SCT');
insert into iso3166 (continent,region,country,capital,code) values ('Europe','Western Europe','Wales','Cardiff','GB-WLS');